server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.31.66:3306
    username: ycj
    password: ycj123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: HTML
  security:
    user:
      name: user
      password: 123456
